spring:
  datasource:
    url: jdbc:mysql://192.168.56.112:3339/robot?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&&serverTimezone=UTC
    username: chenyubo
    password: tuPjtPFa6RRx1es9
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
logging:
  level:
    root: debug
