name: CI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
          cache: gradle
      - name: Build
        run: ./gradlew :git-action:build

      # 登录Docker Hub

      - name: Login to Docker Hub

        uses: docker/login-action@v1

        with:

          username: ${{ secrets.DOCKER_HUB_USERNAME }}

          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Set up Docker Build

        id: build

        uses: docker/setup-buildx-action@v1

      # build 镜像并push到中央仓库中

      - name: Build and push

        id: docker_build

        uses: docker/build-push-action@v2

        with:

          context: ./

          file: ./git-action/Dockerfile

          push: true

          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/git-action:latest